version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:18.12.1
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            npm install node.js
            echo "--------- The images is Building ------------"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed natnaelf/udagram-api-feed:v4a
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user natnaelf/udagram-api-user:v4a
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend natnaelf/udagram-frontend:local
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy natnaelf/udagram-reverseproxy:v4a
            echo "-------- All images succesfully built----------"
            echo " ------- login in to hub--------"
            docker login -u natnaelf -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push natnaelf/udagram-api-feed:v4a
            docker push natnaelf/udagram-api-user:v4a
            docker push natnaelf/udagram-frontend:local
            docker push natnaelf/udagram-reverseproxy:v4a
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]