apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
spec:
  selector:
    matchLabels:
      run: api-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: api-feed
    spec:
      containers:
      - name: api-feed
        image: docker.io/natnaelf/udagram-api-feed:v4a
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-feed
  name: api-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: api-feed