apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    run: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      run: api-user
  template:
    metadata:
      labels:
        run: api-user
    spec:
      containers:
      - name: api-user
        image: natnaelf/udagram-api-user:v4a
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
             name: env-secret


---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-user
  name: api-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: api-user